name: your_project_name
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  image_picker: ^0.8.4+2
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  shared_preferences: ^2.0.6
  lottie: ^1.2.1
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  url_launcher: ^6.0.9
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/contacts.json
    - assets/app_logo.png
    - assets/running_man.json
    - assets/splash.json
    - assets/pics/image0.jpg
    - assets/pics/image1.jpg
    - assets/pics/image2.jpg
    - assets/pics/image3.jpg
    - assets/pics/image4.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
